spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: nmahendran1459@gmail.com
    password: tkniscqxpdofeofa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
